### ISSUE TITLE
failure to parse Kerberos principal name

### ISSUE THREAD

**Issue by rcritten** [etingof/pyasn1#76]
Getting a traceback trying to parse a Kerberos principal name in 0.3.2-0.3.4 (0.3.1 untested). This worked in 0.2.3 in the freeIPA project.

AttributeError: 'GeneralString' object has no attribute 'asn1Object'

[asn1.txt](https://github.com/etingof/pyasn1/files/1306701/asn1.txt)

**Comment by etingof** [comment]
Ah, yes, fixed in 218acc52cd4574df07536e1bc81bc1eb7a410573.

Thank you!
